# Generated by Django 3.2.3 on 2021-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_pessoa_cli', models.CharField(max_length=10)),
                ('nome_cli', models.CharField(max_length=50)),
                ('tell_cli', models.CharField(max_length=15)),
                ('cell_cli', models.CharField(max_length=15)),
                ('cell2_cli', models.CharField(max_length=15)),
                ('email_cli', models.EmailField(max_length=254)),
                ('email2_cli', models.EmailField(max_length=254)),
                ('cgc_cli', models.CharField(max_length=15)),
                ('cnpj_cli', models.CharField(max_length=30)),
                ('cep_cli', models.CharField(max_length=8)),
                ('uf_cli', models.CharField(max_length=2)),
                ('cidade_cli', models.CharField(max_length=30)),
                ('bairro_cli', models.CharField(max_length=30)),
                ('endereco_cli', models.CharField(max_length=50)),
                ('num_cli', models.PositiveIntegerField()),
                ('comp_cli', models.CharField(max_length=100)),
            ],
        ),
    ]
